### ISSUE TITLE
test issue, bug or todo

### ISSUE THREAD

**Issue by 1v06** [1v06/test-legendary-repo2#1]
- [ ] hey @1v06 this issue
>**you son of a bling blob ;)**
this should appear bold
- [ ] this bug, as shown in this vid
[http://github.com](url)
- [ ] #this tag links to a tag
- [ ] *ital*
- [ ] http://github.com - automatic!
[GitHub](http://github.com)
As Kanye West said:

> We're living the future so
> the present is our past.

I think you should use an
`<addr>` element here instead.
`<this acode>`

**Comment by 1v06** [comment]
imma lock this issue now.

>asta la vista baby

**Comment by 1v06** [comment]
oh look i can reopen the issue for you!

#this is a header

i just updated this comment. so no need to write a separate comment!

**Comment by 1v06** [comment]
all good, all fine. gonna close this comment monologue now.
